# Generated by Django 3.2.5 on 2022-08-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
