# Generated by Django 3.2.5 on 2022-08-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0004_alter_item_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
